-- 잊기 전에 한 번 더 정답

-- 6-1
SELECT EMPNO, TO_CHAR() AS MASKING_EMPNO, ENAME, TO_CHAR() AS MASKING_ENAME
FROM EMP
WHERE LENGTH(ENAME) >= 5 AND LENGTH(ENAME) < 6;

-- TO_CHAR 함수는 문자가 아닌 것을 문자로 변환할 때 쓰인다.
-- 그러므로 SUBSTR으로 잘라낸 뒤, PADDING 처리를 하는 것이 올바른 정답이다.

-- 6-1 답
SELECT EMPNO,
       RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO,
       ENAME,
       RPAD(SUBSTR(ENAME, 1, 1), LENGTH(ENAME), '*') AS MASKING_ENAME
 FROM EMP
 WHERE LENGTH(ENAME) >= 5
   AND LENGTH(ENAME) < 6; 


-- 6-2
SELECT EMPNO, ENAME, SAL, TRUNC(800/21.5,3) AS DAY_PAY, ROUND(DAY_PAY/8,2) AS TIME_PAY
FROM EMP;

-- TRUNC 함수와 ROUND 함수 위치 주의! (DAY_PAY) 세 번째자리에서 버리고, (TIME_PAY) 는 두 번째 소수점에서 반올림하세요.
-- 6-2 답
SELECT EMPNO, ENAME, SAL,
       TRUNC(SAL / 21.5, 2) AS DAY_PAY,
       ROUND(SAL / 21.5 / 8, 1) AS TIME_PAY
  FROM EMP; 




-- 6-3


-- 6-4
SELECT EMPNO, ENAME, MGR, 
  CASE
    WHEN MGR IS NULL THEN '0000'
    WHEN SUBSTR(MGR,1,2) == '75' THEN '5555'
    WHEN SUBSTR(MGR,1,2) == '76' THEN '6666'
    WHEN SUBSTR(MGR,1,2) == '77' THEN '7777'
    WHEN SUBSTR(MGR,1,2) == '78' THEN '8888'
    ELSE TO_CHAR(MGR)
  END AS CHG_MGR
FROM EMP;





-- 6-4
SELECT EMPNO, ENAME, MGR,
       CASE
          WHEN MGR IS NULL THEN '0000'
          WHEN SUBSTR(MGR, 1, 2) = '78' THEN '8888'
          WHEN SUBSTR(MGR, 1, 2) = '77' THEN '7777'
          WHEN SUBSTR(MGR, 1, 2) = '76' THEN '6666'
          WHEN SUBSTR(MGR, 1, 2) = '75' THEN '5555'
          ELSE TO_CHAR(MGR)
       END AS CHG_MGR
  FROM EMP;



-- 6-1
SELECT EMPNO,
       RPAD(SUBSTR(EMPNO, 1, 2), 4, '*') AS MASKING_EMPNO,
       ENAME,
       RPAD(SUBSTR(ENAME, 1, 1), LENGTH(ENAME), '*') AS MASKING_ENAME
 FROM  EMP
 WHERE LENGTH(ENAME) >= 5
   AND LENGTH(ENAME) < 6; 

-- 6-2
SELECT EMPNO, ENAME, SAL,
       TRUNC(SAL / 21.5, 2) AS DAY_PAY,
       ROUND(SAL / 21.5 / 8, 1) AS TIME_PAY
  FROM EMP; 

-- 6-3
SELECT EMPNO, ENAME, HIREDATE,
       TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE, 3), '월요일'), 'YYYY-MM-DD') AS R_JOB,
       NVL(TO_CHAR(COMM), 'N/A') AS COMM
  FROM EMP; 

-- 6-4
SELECT EMPNO, ENAME, MGR,
       CASE
          WHEN MGR IS NULL THEN '0000'
          WHEN SUBSTR(MGR, 1, 2) = '78' THEN '8888'
          WHEN SUBSTR(MGR, 1, 2) = '77' THEN '7777'
          WHEN SUBSTR(MGR, 1, 2) = '76' THEN '6666'
          WHEN SUBSTR(MGR, 1, 2) = '75' THEN '5555'
          ELSE TO_CHAR(MGR)
       END AS CHG_MGR
  FROM EMP;
