-- 잊기 전에 한 번 더 정답
-- 편의를 위해 정답과 다른 SQL만 기재
-- 5-1
SELECT *
  FROM EMP
 WHERE ENAME LIKE '%S';

-- 5-2
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP 
 WHERE DEPTNO = 30
   AND JOB = 'SALESMAN';

-- 5-3
-- 집합연산자를 사용하지 않은 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO IN (20, 30) 
   AND SAL > 2000;

-- 집합연산자를 사용한 방식
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 20
   AND SAL > 2000
UNION
SELECT EMPNO, ENAME, JOB, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND SAL > 2000;

-- 5-4
SELECT * 
  FROM EMP
 WHERE SAL < 2000
    OR SAL > 3000;

-- 5-4 내가 작성한 답안
SELECT *
  FROM EMP
MINUS 
SELECT * 
  FROM EMP  
  WHERE SAL BETWEEN 2000 AND 3000;
 
-- 5-5
SELECT ENAME, EMPNO, SAL, DEPTNO
  FROM EMP
 WHERE DEPTNO = 30
   AND ENAME LIKE '%E%'
   AND SAL NOT BETWEEN 1000 AND 2000;

-- 5-5 내가 작성한 답안

SELECT * 
   FROM EMP 
  WHERE ENAME LIKE '%E%'   
    AND DEPTNO = 30
MINUS 
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 2000;  

-- 5-6
SELECT *
  FROM EMP
 WHERE COMM IS NULL
   AND MGR IS NOT NULL
   AND JOB IN ('MANAGER', 'CLERK')
   AND ENAME NOT LIKE '_L%';
