-- 잊기 전에 한 번 더 정답

-- 내가 작성한 답
-- ⭐ TRUNC 함수 잘 파악하기
SELECT DEPTNO, AVG(SAL) AS AVG_SAL, MAX(SAL) AS MAX_SAL, MIN(SAL) AS MIN_SAL, COUNT(*) AS CNT
FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO DESC;

-- 7-1
SELECT DEPTNO,
       TRUNC(AVG(SAL)) AS AVG_SAL,
       MAX(SAL) AS MAX_SAL,
       MIN(SAL) AS MIN_SAL,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY DEPTNO; 


-- 내가 작성한 답
SELECT JOB, COUNT(*)
FROM EMP
GROUP BY JOB
  HAVING COUNT(*) >= 3;


-- 7-2
SELECT JOB,
       COUNT(*)
  FROM EMP
GROUP BY JOB
HAVING COUNT(*) >= 3; 



-- 내가 작성한 답
-- ⭐ TO_CHAR(HIREDATE, 'YYYY') 함수 기억하기
-- ⭐ DEPTNO도 그룹화 되어 있는지 아닌지도 잘 파악할 것
SELECT HIRE_YEAR, DEPTNO, COUNT(*)CNT
FROM EMP
GROUP BY(HIRE_YEAR)

-- 7-3
SELECT TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       DEPTNO,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY TO_CHAR(HIREDATE, 'YYYY'), DEPTNO; 


-- 내가 작성한 답
-- ⭐ GROUP BY 적용이 되었는지 제발 잘 보자... 
SELECT NVL2(COMM,'X','O') AS EXIST_COMM, COUNT(*) AS CNT
FROM EMP


-- 7-4
SELECT NVL2(COMM, 'O', 'X') AS EXIST_COMM,
       COUNT(*) AS CNT
  FROM EMP
GROUP BY NVL2(COMM, 'O', 'X'); 


-- 내가 작성한 답
-- 7-5
SELECT DEPTNO,
       TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       COUNT(*) AS CNT,
       MAX(SAL) AS MAX_SAL,
       SUM(SAL) AS SUM_SAL,
       AVG(SAL) AS AVG_SAL
  FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY')); 



-- 7-5
SELECT DEPTNO,
       TO_CHAR(HIREDATE, 'YYYY') AS HIRE_YEAR,
       COUNT(*) AS CNT,
       MAX(SAL) AS MAX_SAL,
       SUM(SAL) AS SUM_SAL,
       AVG(SAL) AS AVG_SAL
  FROM EMP
GROUP BY ROLLUP(DEPTNO, TO_CHAR(HIREDATE, 'YYYY')); 

